name: "Setup"
description: "Setup a repo using turbo & pnpm."

inputs:
  fetch-depth:
    default: 1
    required: false
  node-version:
    description: "Version of Node.js to use."
    default: "18"
    required: false
  pnpm-version:
    description: "Version of pnpm to use."
    default: "7"
    required: false
  turbo-cache-directory:
    description: "Cache directoy for Turbo."
    default: "./.turbo-cache"
    required: false

outputs:
  turbo-cache-dir:
    description: "Cache directoy of turbo artefacts."
    value: ${{ steps.turbo-cache.outputs.cache-dir }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Expose pnpm Store Path
      id: pnpm-store-path
      shell: bash
      run: echo "store-path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store-path.outputs.store-path }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Expose Turbo Cache Directory
      shell: bash
      run: echo turbo-cache-directory=${{ inputs.turbo-cache-directory }} >> $GITHUB_OUTPUT

    - name: Setup Turbo Cache
      id: turbo-cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.turbo-cache-directory }}
        key: ${{ runner.os }}-turbo-cache-${{ github.sha }}
        restore-keys: ${{ runner.os }}-turbo-cache-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
