name: "Setup"
description: "Setup a repo using turbo & pnpm."

inputs:
  fetch-depth:
    default: 1
    required: false
  node-version:
    description: "Version of Node.js to use."
    default: "v18"
    required: false
  pnpm-version:
    description: "Version of pnpm to use."
    default: "7"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2

    - name: Expose pnpm Store Path
      id: pnpm-store-path
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      shell: bash
      run: pnpm install --forzen-lockfile --prefer-offline
