name: Test Composite Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./turbo/setup
        id: setup
        with:
          working-directory: ./turbo/setup/tests/default
      - run: pnpm build --cache-dir=${{ steps.setup.outputs.turbo-cache-directory }}
        working-directory: ./turbo/setup/tests/default
