name: Test Composite Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: turbo/setup/tests/default
    steps:
      - uses: ../../turbo/setup
