name: Test Composite Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./turbo/setup
        working-directory: turbo/setup/tests/default
